# --------------------
# Define non-modifiable values
# --------------------


# ==================== Alas ====================

Alas:
  Emulator:
    ScreenshotMethod: scrcpy
    ControlMethod: MaaTouch
Restart:
  Scheduler:
    Enable:
      value: true
      display: disabled
    ServerUpdate: 00:00

# ==================== Farm ====================


# ==================== Daily ====================


# ==================== Tools ====================
