# --------------------
# Define non-modifiable values
# --------------------


# ==================== Alas ====================

Restart:
  Scheduler:
    Enable:
      value: true
      display: disabled
    ServerUpdate: 00:00

# ==================== Farm ====================


# ==================== Daily ====================


# ==================== Tools ====================
