# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Alas ====================

Alas:
  - Emulator
  - EmulatorInfo
  - Error
  - Optimization
Restart:
  - Scheduler

# ==================== Farm ====================


# ==================== Daily ====================


# ==================== Tools ====================
